#include <cctype>
#include <cstddef>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <string>
#include <vector>

namespace fs = std::filesystem;

namespace {

void PrintUsage(const wchar_t* executable)
{
    std::wcerr << L"Usage: " << executable
               << L" <input-file> [output-header] [array-name]\n";
}

std::string MakeIdentifier(std::string value)
{
    std::string identifier;
    identifier.reserve(value.size() + 1);

    for (unsigned char character : value) {
        if (std::isalnum(character) || character == '_') {
            identifier.push_back(static_cast<char>(character));
        }
    }

    if (identifier.empty()) {
        identifier = "data";
    }

    if (std::isdigit(static_cast<unsigned char>(identifier.front()))) {
        identifier.insert(identifier.begin(), '_');
    }

    return identifier;
}

bool GenerateCode(const fs::path& inputPath, const fs::path& outputPath,
                  const std::string& arrayName)
{
    std::ifstream input(inputPath, std::ios::binary);
    if (!input) {
        std::wcerr << L"Unable to open input file: " << inputPath << L'\n';
        return false;
    }

    const std::vector<unsigned char> bytes{
        std::istreambuf_iterator<char>(input), std::istreambuf_iterator<char>()};
    if (input.bad()) {
        std::wcerr << L"Unable to read input file: " << inputPath << L'\n';
        return false;
    }

    std::ofstream output(outputPath, std::ios::trunc);
    if (!output) {
        std::wcerr << L"Unable to create output header: " << outputPath << L'\n';
        return false;
    }

    output << "// Generated by file-to-byte-array. Do not edit.\n"
           << "#pragma once\n\n"
           << "#include <cstddef>\n\n";

    // Keep an addressable one-byte array for empty files while exposing the
    // actual source size through the companion constant.
    if (bytes.empty()) {
        output << "inline constexpr unsigned char " << arrayName
               << "[1] = { 0x00 };\n";
    } else {
        output << "inline constexpr unsigned char " << arrayName << "[] = {\n";

        output << std::hex << std::uppercase << std::setfill('0');
        for (std::size_t index = 0; index < bytes.size(); ++index) {
            if (index % 16 == 0) {
                output << "    ";
            }

            output << "0x" << std::setw(2)
                   << static_cast<unsigned int>(bytes[index]);

            if (index + 1 != bytes.size()) {
                output << ", ";
            }

            if (index % 16 == 15 || index + 1 == bytes.size()) {
                output << '\n';
            }
        }

        output << "};\n";
    }

    output << "inline constexpr std::size_t " << arrayName << "_size = "
           << std::dec << bytes.size() << ";\n";

    if (!output) {
        std::wcerr << L"Unable to write output header: " << outputPath << L'\n';
        return false;
    }

    std::wcout << L"Converted " << inputPath << L" (" << bytes.size()
               << L" bytes) to " << outputPath << L'\n';
    return true;
}

} // namespace

int wmain(int argc, wchar_t* argv[])
{
    if (argc < 2 || argc > 4) {
        PrintUsage(argv[0]);
        return 2;
    }

    const fs::path inputPath(argv[1]);
    const fs::path outputPath = argc >= 3
        ? fs::path(argv[2])
        : fs::path(inputPath.stem().wstring() + L".h");
    const std::string arrayName = argc >= 4
        ? MakeIdentifier(fs::path(argv[3]).string())
        : MakeIdentifier(inputPath.stem().string());

    return GenerateCode(inputPath, outputPath, arrayName) ? 0 : 1;
}
